client_config_backend: file
client_config_file: "ucl-master-project/misc/client_secrets.json"
save_credentials: True
oauth_scope: ["https://www.googleapis.com/auth/drive"]

save_credentials_backend: file
save_credentials_file: "ucl-master-project/misc/credentials.json"
