client_config_backend: file
client_config_file: "ucl-master-project/misc/client_secrets.json"
oauth_scope: ["https://www.googleapis.com/auth/drive"]

save_credentials: True
save_credentials_backend: file
save_credentials_file: "ucl-master-project/misc/credentials.json"

get_refresh_token = True